# Generated by Django 3.2.6 on 2023-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
